# Generated by Django 3.2.11 on 2023-02-08 09:26

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import newsletter.core.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created', '-modified']},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=newsletter.core.utils.upload_location, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='image alt'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='meta_description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='meta_title',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish datetime'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='time_to_read',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='title'),
        ),
    ]
