# Generated by Django 3.2.11 on 2023-02-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0002_auto_20230208_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
    ]
