# Generated by Django 3.2.11 on 2023-02-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0003_newsletter_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='news',
            new_name='update',
        ),
    ]
