# Generated by Django 3.2.11 on 2023-02-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0005_newsletter_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='practical',
            new_name='practicals',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='update',
            new_name='updates',
        ),
    ]
