# Generated by Django 3.2.11 on 2023-02-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0006_auto_20230213_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='title'),
        ),
    ]
