# Generated by Django 3.2.11 on 2023-02-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0007_alter_newsletter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='practicals',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='updates',
        ),
    ]
