# Generated by Django 3.2.11 on 2023-02-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_update_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'verbose_name': 'Update'},
        ),
    ]
