# Generated by Django 3.2.11 on 2023-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_update_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='region',
            field=models.CharField(blank=True, choices=[('MiddleEast', 'MiddleEast'), ('Around The World', 'Around The World')], max_length=100, null=True, verbose_name='Region'),
        ),
    ]
