# Generated by Django 3.2.11 on 2023-02-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practical',
            options={'verbose_name': 'Practical'},
        ),
        migrations.AddField(
            model_name='practical',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
    ]
