# Generated by Django 3.2.11 on 2023-02-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0002_auto_20230208_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='practical',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
    ]
