# Generated by Django 3.2.11 on 2023-02-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0003_practical_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practical',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='title'),
        ),
    ]
