# Generated by Django 3.2.11 on 2023-02-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0008_auto_20230215_0958'),
        ('practicals', '0004_alter_practical_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='practical',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletterapp.newsletter'),
        ),
    ]
