# Generated by Django 3.2.11 on 2023-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'SUbscribe Email',
            },
        ),
    ]
